### PR TITLE
hooks: add cloud-init

### PR DESCRIPTION
**Pull request by mvo5**
This is required to make UC18 deployable with MAAS

### CODE REVIEW

**Review by sil2100 — CHANGES_REQUESTED** [review]
As per discussions, we wait with this. We'll probably go a different path.

**Comment by mvo5** [comment]
We discussed this again and the idea was to go with that for UC18 and look into properly snaping cloud-init for UC20. Could @sil2100 or @vorlonofportland please review?

**Review by sil2100 — APPROVED** [review]
So I looked at it on Friday before EOD and it's a +1 from me. Actually what I was surprised about is that the addition of cloud-init seemed to only increase the size of the snap by 1MB - which is much less than I expected. Probably some of the pulled in dependencies are already installed by other pieces.

**Comment by mvo5** [comment]
Thanks @sil2100 :heart:

**Comment by mvo5** [comment]
This is in the beta channel now! Lets kick of validation @sil2100 @sergiocazzolato

**Comment by sergiocazzolato** [comment]
@mvo5 could not start the image with the core snap, see logs https://paste.ubuntu.com/p/NQGkyDjdHN/
going to try a refresh from stable now

**Comment by vorlonofportland** [comment]
My understanding of the discussion last week was that, *if* we were confident that there was a path forward to add hooks to the core18 snap that would use an external cloud-init snap if present, we could proceed with releasing UC18 as-is and add the cloud-init hooks post-release.

However, @mvo5 if you are satisfied that the 1MB increase in disk size is within reason, then I don't object to this approach.

**Comment by sil2100** [comment]
@vorlonofportland on Friday we had one more discussion about it in the afternoon with Mark and the final conclusion was: let's just add it as is.

**Comment by mvo5** [comment]
@sergiocazzolato Could this be the entropy issue, i.e. it was hanging for a long time because the 4.15 kernel is stricter about entropy?

**Pull request merged**
