### PR TITLE
hooks: install net-tools package

### PR DESCRIPTION
**Pull request by mvo5**
This will add ifconfig/netstat to core18 which is useful in the
tests and more convinient for admins than using "ip".

### CODE REVIEW

**Review by sil2100 — APPROVED** [review]
LGTM

**Comment by zyga** [comment]
Hmm, hmm, not sure if we should do this. Yes it is more helpful but 1) 18.04 doesn't ship it by default 2) it's deprecated 3) the reasons for deprecating it were that it doesn't handle new things very well.

Do you plan to remove it before core18 ships?

I'm -1 myself.

**Comment by mvo5** [comment]
@zyga Thank you, we can fix the tests, we use netstat there quite a bit.

**Comment by zyga** [comment]
@mvo5 would a netstat snap work? I mean, I don't oppose _using_ netstat, I oppse _shipping_ it as supported for 18 cycle.

**Comment by mvo5** [comment]
Closing for now while investigating alternatives

**Pull request closed without merging**
