### PR TITLE
Test timezone contents and symlink.

### PR DESCRIPTION
**Pull request by xnox**

### CODE REVIEW

**Review by mvo5 — COMMENTED** [review]
Loosk good, thanks for adding the test.

However the one thing that is not ideal is that this test is in 008- but the actual manipulation of the timezone stuff is done in 030- or am I missing something?

**Comment by xnox** [comment]
we run all hooks, then all tests. Thus 008 test is after both 008- and 030- hooks have run.

Arguably this is split in two places. So i could move the
```
test $(readlink etc/writable/localtime) = "/usr/share/zoneinfo/Etc/UTC"
```
from the 008- to 030- test.

**Comment by xnox** [comment]
030-* changes to timezone is redundant code.

**Review by mvo5 — APPROVED** [review]
nice

**Pull request merged**
