### PR TITLE
Switch travis CI to xenial, add a snap wait after installing snapd to…

### PR DESCRIPTION
**Pull request by sil2100**
… make sure we're ready before installing new snaps.

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]

**Review by zyga — APPROVED** [review]
I want this to work :)

**Comment by zyga** [comment]
This is failing a little bit and the output is very noisy due to the progress bar. I know @mvo5 likes the new `apt` command but perhaps we should switch to `apt-get` here?

**Comment by mvo5** [comment]
From my side its fine to switch to apt-get or just use "apt -qq" to have less progress (I actually wonder if we honor -qq in the install progress)

**Comment by sil2100** [comment]
Thanks for reviews! THis seems to work-ish, so yeah, let me merge it. We can become a bit more quiet indeed for readability.

**Pull request merged**
