### PR TITLE
hooks: clenup /etc/{passwd,shadow,group,gshadow}.orig

### PR DESCRIPTION
**Pull request by mvo5**
Trivial followup from https://github.com/snapcore/core18/pull/28

### CODE REVIEW

**Review by zyga — APPROVED** [review]
+1

**Review by sil2100 — CHANGES_REQUESTED** [review]
Yeah, forgot about this completely, was hurrying too much to get it PRed. Big +1! But the CI shellcheck is right - brace expansion might be tricky here if we're using /bin/sh. We'd either need to switch to bash here or something like this:

for f in passwd shadow group gshadow; do
        rm /etc/$f.orig
done

**Review by sil2100 — APPROVED** [review]
Now it's green, merging.

**Comment by sil2100** [comment]
Thanks!

**Pull request merged**
