### PR TITLE
run-snapd-from-snap: lazily umount snapd

### PR DESCRIPTION
**Pull request by valentindavid**

### CODE REVIEW

**Comment by valentindavid** [comment]
I have found this potential issue in tests of https://github.com/snapcore/snapd/pull/13517

**Comment by valentindavid** [comment]
The reason why it fails is probably due to snapd still running until new instance starts, which will happen some time after the umount. But snapd might have memory mapped some libraries from the snapd snap. Thus the snap cannot be unmounted until we it is fully restarted.

**Review by alfonsosanchezbeato — COMMENTED** [review]
LGTM

**Review by alfonsosanchezbeato — APPROVED** [review]

**Comment by alfonsosanchezbeato** [comment]
Is this needed in any other base? Just noticed this is core18

**Pull request merged**
