### PR TITLE
Add pollinate to the extra packages

### PR DESCRIPTION
**Pull request by rcj4747**

### CODE REVIEW

**Review by mvo5 — APPROVED** [review]
Thank you!

**Comment by rcj4747** [comment]
> Thank you!

@mvo5 Well, my idea was good, but the execution based on the test failure was incomplete.  I incorrectly thought I could offer up a drive-by patch to help myself.  I might need a bit of help to address the failures.

**Comment by mvo5** [comment]
There is also the issue that the pollinate shell script needs some tweaks, i.e. it uses lsb_release and dpkg today which is not available on core.

**Comment by mvo5** [comment]
I looked into pollinate a bit more today and started to port it so that it works on ubuntu-core. However it turns out that there is no curl in core18. So it looks like we need to add this as well. Here is my diff https://paste.ubuntu.com/p/VwPPkykHjP/

**Pull request closed without merging**
